# -*- coding: utf-8 -*-
"""CTD_prework_Ikechukwu_Ikekwem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AY7pCSN9GrVkUu0DR3aE9ck23WerHUWE
"""

# This script verifies age of applicants for a job vacancy
#first input takes user's name and the second input age
# Only users 18 or older can move forward with the job application
info1 = input("Please enter your name: ")
info2_str = input("Please insert age: ")

try:
    info2_num = int(info2_str)
    if info2_num < 18:
        print(f"Sorry {info1} only those above 18 can move forward with this application")
    else:
        print(f"Congrats! {info1} you are eligible to apply for this position")
except ValueError:
    print(f"You entered {info1} and {info2_str}. The input is invalid, please try again")